namespace CatalogProject
{
    partial class MainForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainForm));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.DataSettingBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnCompanySetting = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnCategorySetting = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnProductsSetting = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnProductSetting = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.SuspendLayout();
            // 
            // DataSettingBtn
            // 
            this.DataSettingBtn.AllowAnimations = true;
            this.DataSettingBtn.AllowMouseEffects = true;
            this.DataSettingBtn.AllowToggling = false;
            this.DataSettingBtn.AnimationSpeed = 200;
            this.DataSettingBtn.AutoGenerateColors = false;
            this.DataSettingBtn.AutoRoundBorders = false;
            this.DataSettingBtn.AutoSizeLeftIcon = true;
            this.DataSettingBtn.AutoSizeRightIcon = true;
            this.DataSettingBtn.BackColor = System.Drawing.Color.Transparent;
            this.DataSettingBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.DataSettingBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("DataSettingBtn.BackgroundImage")));
            this.DataSettingBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.DataSettingBtn.ButtonText = "تنظیمات دیتا";
            this.DataSettingBtn.ButtonTextMarginLeft = 0;
            this.DataSettingBtn.ColorContrastOnClick = 45;
            this.DataSettingBtn.ColorContrastOnHover = 45;
            this.DataSettingBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.DataSettingBtn.CustomizableEdges = borderEdges1;
            this.DataSettingBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.DataSettingBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.DataSettingBtn.DisabledFillColor = System.Drawing.Color.Empty;
            this.DataSettingBtn.DisabledForecolor = System.Drawing.Color.Empty;
            this.DataSettingBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.DataSettingBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.DataSettingBtn.ForeColor = System.Drawing.Color.White;
            this.DataSettingBtn.IconLeft = null;
            this.DataSettingBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.DataSettingBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.DataSettingBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.DataSettingBtn.IconMarginLeft = 11;
            this.DataSettingBtn.IconPadding = 10;
            this.DataSettingBtn.IconRight = null;
            this.DataSettingBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.DataSettingBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.DataSettingBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.DataSettingBtn.IconSize = 25;
            this.DataSettingBtn.IdleBorderColor = System.Drawing.Color.Empty;
            this.DataSettingBtn.IdleBorderRadius = 0;
            this.DataSettingBtn.IdleBorderThickness = 0;
            this.DataSettingBtn.IdleFillColor = System.Drawing.Color.Empty;
            this.DataSettingBtn.IdleIconLeftImage = null;
            this.DataSettingBtn.IdleIconRightImage = null;
            this.DataSettingBtn.IndicateFocus = false;
            this.DataSettingBtn.Location = new System.Drawing.Point(132, 49);
            this.DataSettingBtn.Name = "DataSettingBtn";
            this.DataSettingBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.DataSettingBtn.OnDisabledState.BorderRadius = 1;
            this.DataSettingBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.DataSettingBtn.OnDisabledState.BorderThickness = 1;
            this.DataSettingBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.DataSettingBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.DataSettingBtn.OnDisabledState.IconLeftImage = null;
            this.DataSettingBtn.OnDisabledState.IconRightImage = null;
            this.DataSettingBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.DataSettingBtn.onHoverState.BorderRadius = 1;
            this.DataSettingBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.DataSettingBtn.onHoverState.BorderThickness = 1;
            this.DataSettingBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.DataSettingBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.DataSettingBtn.onHoverState.IconLeftImage = null;
            this.DataSettingBtn.onHoverState.IconRightImage = null;
            this.DataSettingBtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.DataSettingBtn.OnIdleState.BorderRadius = 1;
            this.DataSettingBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.DataSettingBtn.OnIdleState.BorderThickness = 1;
            this.DataSettingBtn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.DataSettingBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.DataSettingBtn.OnIdleState.IconLeftImage = null;
            this.DataSettingBtn.OnIdleState.IconRightImage = null;
            this.DataSettingBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.DataSettingBtn.OnPressedState.BorderRadius = 1;
            this.DataSettingBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.DataSettingBtn.OnPressedState.BorderThickness = 1;
            this.DataSettingBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.DataSettingBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.DataSettingBtn.OnPressedState.IconLeftImage = null;
            this.DataSettingBtn.OnPressedState.IconRightImage = null;
            this.DataSettingBtn.Size = new System.Drawing.Size(150, 39);
            this.DataSettingBtn.TabIndex = 0;
            this.DataSettingBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.DataSettingBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.DataSettingBtn.TextMarginLeft = 0;
            this.DataSettingBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.DataSettingBtn.UseDefaultRadiusAndThickness = true;
            this.DataSettingBtn.Click += new System.EventHandler(this.DataSettingBtn_Click);
            // 
            // bunifuButton2
            // 
            this.bunifuButton2.AllowAnimations = true;
            this.bunifuButton2.AllowMouseEffects = true;
            this.bunifuButton2.AllowToggling = false;
            this.bunifuButton2.AnimationSpeed = 200;
            this.bunifuButton2.AutoGenerateColors = false;
            this.bunifuButton2.AutoRoundBorders = false;
            this.bunifuButton2.AutoSizeLeftIcon = true;
            this.bunifuButton2.AutoSizeRightIcon = true;
            this.bunifuButton2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton2.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.bunifuButton2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton2.BackgroundImage")));
            this.bunifuButton2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.ButtonText = "bunifuButton1";
            this.bunifuButton2.ButtonTextMarginLeft = 0;
            this.bunifuButton2.ColorContrastOnClick = 45;
            this.bunifuButton2.ColorContrastOnHover = 45;
            this.bunifuButton2.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bunifuButton2.CustomizableEdges = borderEdges2;
            this.bunifuButton2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton2.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.DisabledFillColor = System.Drawing.Color.Empty;
            this.bunifuButton2.DisabledForecolor = System.Drawing.Color.Empty;
            this.bunifuButton2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton2.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuButton2.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.IconLeft = null;
            this.bunifuButton2.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton2.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton2.IconMarginLeft = 11;
            this.bunifuButton2.IconPadding = 10;
            this.bunifuButton2.IconRight = null;
            this.bunifuButton2.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton2.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton2.IconSize = 25;
            this.bunifuButton2.IdleBorderColor = System.Drawing.Color.Empty;
            this.bunifuButton2.IdleBorderRadius = 0;
            this.bunifuButton2.IdleBorderThickness = 0;
            this.bunifuButton2.IdleFillColor = System.Drawing.Color.Empty;
            this.bunifuButton2.IdleIconLeftImage = null;
            this.bunifuButton2.IdleIconRightImage = null;
            this.bunifuButton2.IndicateFocus = false;
            this.bunifuButton2.Location = new System.Drawing.Point(132, 94);
            this.bunifuButton2.Name = "bunifuButton2";
            this.bunifuButton2.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.OnDisabledState.BorderRadius = 1;
            this.bunifuButton2.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnDisabledState.BorderThickness = 1;
            this.bunifuButton2.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton2.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton2.OnDisabledState.IconLeftImage = null;
            this.bunifuButton2.OnDisabledState.IconRightImage = null;
            this.bunifuButton2.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton2.onHoverState.BorderRadius = 1;
            this.bunifuButton2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.onHoverState.BorderThickness = 1;
            this.bunifuButton2.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton2.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.onHoverState.IconLeftImage = null;
            this.bunifuButton2.onHoverState.IconRightImage = null;
            this.bunifuButton2.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton2.OnIdleState.BorderRadius = 1;
            this.bunifuButton2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnIdleState.BorderThickness = 1;
            this.bunifuButton2.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton2.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.OnIdleState.IconLeftImage = null;
            this.bunifuButton2.OnIdleState.IconRightImage = null;
            this.bunifuButton2.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnPressedState.BorderRadius = 1;
            this.bunifuButton2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnPressedState.BorderThickness = 1;
            this.bunifuButton2.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.OnPressedState.IconLeftImage = null;
            this.bunifuButton2.OnPressedState.IconRightImage = null;
            this.bunifuButton2.Size = new System.Drawing.Size(150, 39);
            this.bunifuButton2.TabIndex = 0;
            this.bunifuButton2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton2.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton2.TextMarginLeft = 0;
            this.bunifuButton2.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton2.UseDefaultRadiusAndThickness = true;
            this.bunifuButton2.Click += new System.EventHandler(this.bunifuButton2_Click);
            // 
            // bunifuButton3
            // 
            this.bunifuButton3.AllowAnimations = true;
            this.bunifuButton3.AllowMouseEffects = true;
            this.bunifuButton3.AllowToggling = false;
            this.bunifuButton3.AnimationSpeed = 200;
            this.bunifuButton3.AutoGenerateColors = false;
            this.bunifuButton3.AutoRoundBorders = false;
            this.bunifuButton3.AutoSizeLeftIcon = true;
            this.bunifuButton3.AutoSizeRightIcon = true;
            this.bunifuButton3.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton3.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.bunifuButton3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton3.BackgroundImage")));
            this.bunifuButton3.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.ButtonText = "bunifuButton1";
            this.bunifuButton3.ButtonTextMarginLeft = 0;
            this.bunifuButton3.ColorContrastOnClick = 45;
            this.bunifuButton3.ColorContrastOnHover = 45;
            this.bunifuButton3.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.bunifuButton3.CustomizableEdges = borderEdges3;
            this.bunifuButton3.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton3.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton3.DisabledFillColor = System.Drawing.Color.Empty;
            this.bunifuButton3.DisabledForecolor = System.Drawing.Color.Empty;
            this.bunifuButton3.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton3.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuButton3.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.IconLeft = null;
            this.bunifuButton3.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton3.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton3.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton3.IconMarginLeft = 11;
            this.bunifuButton3.IconPadding = 10;
            this.bunifuButton3.IconRight = null;
            this.bunifuButton3.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton3.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton3.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton3.IconSize = 25;
            this.bunifuButton3.IdleBorderColor = System.Drawing.Color.Empty;
            this.bunifuButton3.IdleBorderRadius = 0;
            this.bunifuButton3.IdleBorderThickness = 0;
            this.bunifuButton3.IdleFillColor = System.Drawing.Color.Empty;
            this.bunifuButton3.IdleIconLeftImage = null;
            this.bunifuButton3.IdleIconRightImage = null;
            this.bunifuButton3.IndicateFocus = false;
            this.bunifuButton3.Location = new System.Drawing.Point(132, 139);
            this.bunifuButton3.Name = "bunifuButton3";
            this.bunifuButton3.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton3.OnDisabledState.BorderRadius = 1;
            this.bunifuButton3.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnDisabledState.BorderThickness = 1;
            this.bunifuButton3.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton3.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton3.OnDisabledState.IconLeftImage = null;
            this.bunifuButton3.OnDisabledState.IconRightImage = null;
            this.bunifuButton3.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton3.onHoverState.BorderRadius = 1;
            this.bunifuButton3.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.onHoverState.BorderThickness = 1;
            this.bunifuButton3.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton3.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.onHoverState.IconLeftImage = null;
            this.bunifuButton3.onHoverState.IconRightImage = null;
            this.bunifuButton3.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton3.OnIdleState.BorderRadius = 1;
            this.bunifuButton3.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnIdleState.BorderThickness = 1;
            this.bunifuButton3.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton3.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.OnIdleState.IconLeftImage = null;
            this.bunifuButton3.OnIdleState.IconRightImage = null;
            this.bunifuButton3.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton3.OnPressedState.BorderRadius = 1;
            this.bunifuButton3.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnPressedState.BorderThickness = 1;
            this.bunifuButton3.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton3.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.OnPressedState.IconLeftImage = null;
            this.bunifuButton3.OnPressedState.IconRightImage = null;
            this.bunifuButton3.Size = new System.Drawing.Size(150, 39);
            this.bunifuButton3.TabIndex = 0;
            this.bunifuButton3.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton3.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton3.TextMarginLeft = 0;
            this.bunifuButton3.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton3.UseDefaultRadiusAndThickness = true;
            this.bunifuButton3.Click += new System.EventHandler(this.bunifuButton3_Click);
            // 
            // btnCompanySetting
            // 
            this.btnCompanySetting.AllowAnimations = true;
            this.btnCompanySetting.AllowMouseEffects = true;
            this.btnCompanySetting.AllowToggling = false;
            this.btnCompanySetting.AnimationSpeed = 200;
            this.btnCompanySetting.AutoGenerateColors = false;
            this.btnCompanySetting.AutoRoundBorders = false;
            this.btnCompanySetting.AutoSizeLeftIcon = true;
            this.btnCompanySetting.AutoSizeRightIcon = true;
            this.btnCompanySetting.BackColor = System.Drawing.Color.Transparent;
            this.btnCompanySetting.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnCompanySetting.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCompanySetting.BackgroundImage")));
            this.btnCompanySetting.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCompanySetting.ButtonText = "تنظیمات صفحه کومپانی";
            this.btnCompanySetting.ButtonTextMarginLeft = 0;
            this.btnCompanySetting.ColorContrastOnClick = 45;
            this.btnCompanySetting.ColorContrastOnHover = 45;
            this.btnCompanySetting.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnCompanySetting.CustomizableEdges = borderEdges4;
            this.btnCompanySetting.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCompanySetting.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCompanySetting.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnCompanySetting.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnCompanySetting.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCompanySetting.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnCompanySetting.ForeColor = System.Drawing.Color.White;
            this.btnCompanySetting.IconLeft = null;
            this.btnCompanySetting.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCompanySetting.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCompanySetting.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCompanySetting.IconMarginLeft = 11;
            this.btnCompanySetting.IconPadding = 10;
            this.btnCompanySetting.IconRight = null;
            this.btnCompanySetting.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCompanySetting.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCompanySetting.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCompanySetting.IconSize = 25;
            this.btnCompanySetting.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnCompanySetting.IdleBorderRadius = 0;
            this.btnCompanySetting.IdleBorderThickness = 0;
            this.btnCompanySetting.IdleFillColor = System.Drawing.Color.Empty;
            this.btnCompanySetting.IdleIconLeftImage = null;
            this.btnCompanySetting.IdleIconRightImage = null;
            this.btnCompanySetting.IndicateFocus = false;
            this.btnCompanySetting.Location = new System.Drawing.Point(301, 49);
            this.btnCompanySetting.Name = "btnCompanySetting";
            this.btnCompanySetting.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCompanySetting.OnDisabledState.BorderRadius = 1;
            this.btnCompanySetting.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCompanySetting.OnDisabledState.BorderThickness = 1;
            this.btnCompanySetting.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCompanySetting.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCompanySetting.OnDisabledState.IconLeftImage = null;
            this.btnCompanySetting.OnDisabledState.IconRightImage = null;
            this.btnCompanySetting.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnCompanySetting.onHoverState.BorderRadius = 1;
            this.btnCompanySetting.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCompanySetting.onHoverState.BorderThickness = 1;
            this.btnCompanySetting.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnCompanySetting.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnCompanySetting.onHoverState.IconLeftImage = null;
            this.btnCompanySetting.onHoverState.IconRightImage = null;
            this.btnCompanySetting.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnCompanySetting.OnIdleState.BorderRadius = 1;
            this.btnCompanySetting.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCompanySetting.OnIdleState.BorderThickness = 1;
            this.btnCompanySetting.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnCompanySetting.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCompanySetting.OnIdleState.IconLeftImage = null;
            this.btnCompanySetting.OnIdleState.IconRightImage = null;
            this.btnCompanySetting.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCompanySetting.OnPressedState.BorderRadius = 1;
            this.btnCompanySetting.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCompanySetting.OnPressedState.BorderThickness = 1;
            this.btnCompanySetting.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCompanySetting.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCompanySetting.OnPressedState.IconLeftImage = null;
            this.btnCompanySetting.OnPressedState.IconRightImage = null;
            this.btnCompanySetting.Size = new System.Drawing.Size(192, 39);
            this.btnCompanySetting.TabIndex = 0;
            this.btnCompanySetting.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCompanySetting.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCompanySetting.TextMarginLeft = 0;
            this.btnCompanySetting.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCompanySetting.UseDefaultRadiusAndThickness = true;
            this.btnCompanySetting.Click += new System.EventHandler(this.btnCompanySetting_Click);
            // 
            // btnCategorySetting
            // 
            this.btnCategorySetting.AllowAnimations = true;
            this.btnCategorySetting.AllowMouseEffects = true;
            this.btnCategorySetting.AllowToggling = false;
            this.btnCategorySetting.AnimationSpeed = 200;
            this.btnCategorySetting.AutoGenerateColors = false;
            this.btnCategorySetting.AutoRoundBorders = false;
            this.btnCategorySetting.AutoSizeLeftIcon = true;
            this.btnCategorySetting.AutoSizeRightIcon = true;
            this.btnCategorySetting.BackColor = System.Drawing.Color.Transparent;
            this.btnCategorySetting.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnCategorySetting.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCategorySetting.BackgroundImage")));
            this.btnCategorySetting.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCategorySetting.ButtonText = "تنظیمات صفحه کتگوری";
            this.btnCategorySetting.ButtonTextMarginLeft = 0;
            this.btnCategorySetting.ColorContrastOnClick = 45;
            this.btnCategorySetting.ColorContrastOnHover = 45;
            this.btnCategorySetting.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnCategorySetting.CustomizableEdges = borderEdges5;
            this.btnCategorySetting.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCategorySetting.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCategorySetting.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnCategorySetting.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnCategorySetting.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCategorySetting.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnCategorySetting.ForeColor = System.Drawing.Color.White;
            this.btnCategorySetting.IconLeft = null;
            this.btnCategorySetting.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCategorySetting.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCategorySetting.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCategorySetting.IconMarginLeft = 11;
            this.btnCategorySetting.IconPadding = 10;
            this.btnCategorySetting.IconRight = null;
            this.btnCategorySetting.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCategorySetting.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCategorySetting.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCategorySetting.IconSize = 25;
            this.btnCategorySetting.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnCategorySetting.IdleBorderRadius = 0;
            this.btnCategorySetting.IdleBorderThickness = 0;
            this.btnCategorySetting.IdleFillColor = System.Drawing.Color.Empty;
            this.btnCategorySetting.IdleIconLeftImage = null;
            this.btnCategorySetting.IdleIconRightImage = null;
            this.btnCategorySetting.IndicateFocus = false;
            this.btnCategorySetting.Location = new System.Drawing.Point(499, 94);
            this.btnCategorySetting.Name = "btnCategorySetting";
            this.btnCategorySetting.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCategorySetting.OnDisabledState.BorderRadius = 1;
            this.btnCategorySetting.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCategorySetting.OnDisabledState.BorderThickness = 1;
            this.btnCategorySetting.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCategorySetting.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCategorySetting.OnDisabledState.IconLeftImage = null;
            this.btnCategorySetting.OnDisabledState.IconRightImage = null;
            this.btnCategorySetting.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnCategorySetting.onHoverState.BorderRadius = 1;
            this.btnCategorySetting.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCategorySetting.onHoverState.BorderThickness = 1;
            this.btnCategorySetting.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnCategorySetting.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnCategorySetting.onHoverState.IconLeftImage = null;
            this.btnCategorySetting.onHoverState.IconRightImage = null;
            this.btnCategorySetting.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnCategorySetting.OnIdleState.BorderRadius = 1;
            this.btnCategorySetting.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCategorySetting.OnIdleState.BorderThickness = 1;
            this.btnCategorySetting.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnCategorySetting.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCategorySetting.OnIdleState.IconLeftImage = null;
            this.btnCategorySetting.OnIdleState.IconRightImage = null;
            this.btnCategorySetting.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCategorySetting.OnPressedState.BorderRadius = 1;
            this.btnCategorySetting.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCategorySetting.OnPressedState.BorderThickness = 1;
            this.btnCategorySetting.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCategorySetting.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCategorySetting.OnPressedState.IconLeftImage = null;
            this.btnCategorySetting.OnPressedState.IconRightImage = null;
            this.btnCategorySetting.Size = new System.Drawing.Size(192, 39);
            this.btnCategorySetting.TabIndex = 0;
            this.btnCategorySetting.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCategorySetting.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCategorySetting.TextMarginLeft = 0;
            this.btnCategorySetting.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCategorySetting.UseDefaultRadiusAndThickness = true;
            this.btnCategorySetting.Click += new System.EventHandler(this.btnCategorySetting_Click);
            // 
            // btnProductsSetting
            // 
            this.btnProductsSetting.AllowAnimations = true;
            this.btnProductsSetting.AllowMouseEffects = true;
            this.btnProductsSetting.AllowToggling = false;
            this.btnProductsSetting.AnimationSpeed = 200;
            this.btnProductsSetting.AutoGenerateColors = false;
            this.btnProductsSetting.AutoRoundBorders = false;
            this.btnProductsSetting.AutoSizeLeftIcon = true;
            this.btnProductsSetting.AutoSizeRightIcon = true;
            this.btnProductsSetting.BackColor = System.Drawing.Color.Transparent;
            this.btnProductsSetting.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnProductsSetting.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnProductsSetting.BackgroundImage")));
            this.btnProductsSetting.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProductsSetting.ButtonText = "تنظیمات صفحه محصولات";
            this.btnProductsSetting.ButtonTextMarginLeft = 0;
            this.btnProductsSetting.ColorContrastOnClick = 45;
            this.btnProductsSetting.ColorContrastOnHover = 45;
            this.btnProductsSetting.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnProductsSetting.CustomizableEdges = borderEdges6;
            this.btnProductsSetting.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnProductsSetting.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnProductsSetting.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnProductsSetting.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnProductsSetting.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnProductsSetting.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnProductsSetting.ForeColor = System.Drawing.Color.White;
            this.btnProductsSetting.IconLeft = null;
            this.btnProductsSetting.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnProductsSetting.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnProductsSetting.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnProductsSetting.IconMarginLeft = 11;
            this.btnProductsSetting.IconPadding = 10;
            this.btnProductsSetting.IconRight = null;
            this.btnProductsSetting.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnProductsSetting.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnProductsSetting.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnProductsSetting.IconSize = 25;
            this.btnProductsSetting.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnProductsSetting.IdleBorderRadius = 0;
            this.btnProductsSetting.IdleBorderThickness = 0;
            this.btnProductsSetting.IdleFillColor = System.Drawing.Color.Empty;
            this.btnProductsSetting.IdleIconLeftImage = null;
            this.btnProductsSetting.IdleIconRightImage = null;
            this.btnProductsSetting.IndicateFocus = false;
            this.btnProductsSetting.Location = new System.Drawing.Point(499, 49);
            this.btnProductsSetting.Name = "btnProductsSetting";
            this.btnProductsSetting.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnProductsSetting.OnDisabledState.BorderRadius = 1;
            this.btnProductsSetting.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProductsSetting.OnDisabledState.BorderThickness = 1;
            this.btnProductsSetting.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnProductsSetting.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnProductsSetting.OnDisabledState.IconLeftImage = null;
            this.btnProductsSetting.OnDisabledState.IconRightImage = null;
            this.btnProductsSetting.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnProductsSetting.onHoverState.BorderRadius = 1;
            this.btnProductsSetting.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProductsSetting.onHoverState.BorderThickness = 1;
            this.btnProductsSetting.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnProductsSetting.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnProductsSetting.onHoverState.IconLeftImage = null;
            this.btnProductsSetting.onHoverState.IconRightImage = null;
            this.btnProductsSetting.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnProductsSetting.OnIdleState.BorderRadius = 1;
            this.btnProductsSetting.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProductsSetting.OnIdleState.BorderThickness = 1;
            this.btnProductsSetting.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnProductsSetting.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnProductsSetting.OnIdleState.IconLeftImage = null;
            this.btnProductsSetting.OnIdleState.IconRightImage = null;
            this.btnProductsSetting.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnProductsSetting.OnPressedState.BorderRadius = 1;
            this.btnProductsSetting.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProductsSetting.OnPressedState.BorderThickness = 1;
            this.btnProductsSetting.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnProductsSetting.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnProductsSetting.OnPressedState.IconLeftImage = null;
            this.btnProductsSetting.OnPressedState.IconRightImage = null;
            this.btnProductsSetting.Size = new System.Drawing.Size(192, 39);
            this.btnProductsSetting.TabIndex = 0;
            this.btnProductsSetting.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnProductsSetting.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnProductsSetting.TextMarginLeft = 0;
            this.btnProductsSetting.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnProductsSetting.UseDefaultRadiusAndThickness = true;
            this.btnProductsSetting.Click += new System.EventHandler(this.btnProductsSetting_Click);
            // 
            // btnProductSetting
            // 
            this.btnProductSetting.AllowAnimations = true;
            this.btnProductSetting.AllowMouseEffects = true;
            this.btnProductSetting.AllowToggling = false;
            this.btnProductSetting.AnimationSpeed = 200;
            this.btnProductSetting.AutoGenerateColors = false;
            this.btnProductSetting.AutoRoundBorders = false;
            this.btnProductSetting.AutoSizeLeftIcon = true;
            this.btnProductSetting.AutoSizeRightIcon = true;
            this.btnProductSetting.BackColor = System.Drawing.Color.Transparent;
            this.btnProductSetting.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnProductSetting.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnProductSetting.BackgroundImage")));
            this.btnProductSetting.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProductSetting.ButtonText = "تنظیمات صفحه محصول";
            this.btnProductSetting.ButtonTextMarginLeft = 0;
            this.btnProductSetting.ColorContrastOnClick = 45;
            this.btnProductSetting.ColorContrastOnHover = 45;
            this.btnProductSetting.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btnProductSetting.CustomizableEdges = borderEdges7;
            this.btnProductSetting.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnProductSetting.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnProductSetting.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnProductSetting.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnProductSetting.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnProductSetting.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnProductSetting.ForeColor = System.Drawing.Color.White;
            this.btnProductSetting.IconLeft = null;
            this.btnProductSetting.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnProductSetting.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnProductSetting.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnProductSetting.IconMarginLeft = 11;
            this.btnProductSetting.IconPadding = 10;
            this.btnProductSetting.IconRight = null;
            this.btnProductSetting.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnProductSetting.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnProductSetting.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnProductSetting.IconSize = 25;
            this.btnProductSetting.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnProductSetting.IdleBorderRadius = 0;
            this.btnProductSetting.IdleBorderThickness = 0;
            this.btnProductSetting.IdleFillColor = System.Drawing.Color.Empty;
            this.btnProductSetting.IdleIconLeftImage = null;
            this.btnProductSetting.IdleIconRightImage = null;
            this.btnProductSetting.IndicateFocus = false;
            this.btnProductSetting.Location = new System.Drawing.Point(301, 94);
            this.btnProductSetting.Name = "btnProductSetting";
            this.btnProductSetting.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnProductSetting.OnDisabledState.BorderRadius = 1;
            this.btnProductSetting.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProductSetting.OnDisabledState.BorderThickness = 1;
            this.btnProductSetting.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnProductSetting.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnProductSetting.OnDisabledState.IconLeftImage = null;
            this.btnProductSetting.OnDisabledState.IconRightImage = null;
            this.btnProductSetting.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnProductSetting.onHoverState.BorderRadius = 1;
            this.btnProductSetting.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProductSetting.onHoverState.BorderThickness = 1;
            this.btnProductSetting.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnProductSetting.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnProductSetting.onHoverState.IconLeftImage = null;
            this.btnProductSetting.onHoverState.IconRightImage = null;
            this.btnProductSetting.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnProductSetting.OnIdleState.BorderRadius = 1;
            this.btnProductSetting.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProductSetting.OnIdleState.BorderThickness = 1;
            this.btnProductSetting.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnProductSetting.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnProductSetting.OnIdleState.IconLeftImage = null;
            this.btnProductSetting.OnIdleState.IconRightImage = null;
            this.btnProductSetting.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnProductSetting.OnPressedState.BorderRadius = 1;
            this.btnProductSetting.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProductSetting.OnPressedState.BorderThickness = 1;
            this.btnProductSetting.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnProductSetting.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnProductSetting.OnPressedState.IconLeftImage = null;
            this.btnProductSetting.OnPressedState.IconRightImage = null;
            this.btnProductSetting.Size = new System.Drawing.Size(192, 39);
            this.btnProductSetting.TabIndex = 0;
            this.btnProductSetting.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnProductSetting.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnProductSetting.TextMarginLeft = 0;
            this.btnProductSetting.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnProductSetting.UseDefaultRadiusAndThickness = true;
            this.btnProductSetting.Click += new System.EventHandler(this.btnProductSetting_Click);
            // 
            // MainForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1063, 715);
            this.Controls.Add(this.bunifuButton3);
            this.Controls.Add(this.btnProductSetting);
            this.Controls.Add(this.btnProductsSetting);
            this.Controls.Add(this.btnCategorySetting);
            this.Controls.Add(this.btnCompanySetting);
            this.Controls.Add(this.bunifuButton2);
            this.Controls.Add(this.DataSettingBtn);
            this.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.Name = "MainForm";
            this.Text = "MainForm";
            this.Load += new System.EventHandler(this.MainForm_Load);
            this.ResumeLayout(false);

        }

        #endregion

       
        private System.Windows.Forms.Timer timer1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton DataSettingBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCompanySetting;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCategorySetting;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnProductsSetting;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnProductSetting;
    }
}